# Generated by Django 4.0.3 on 2022-04-25 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_name',
            new_name='employee_last_name',
        ),
    ]
