# Generated by Django 4.0.3 on 2022-04-25 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_rename_employee_name_employee_employee_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('pointage_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('entry_time', models.TimeField(auto_now=True)),
                ('exit_time', models.TimeField(auto_now=True)),
                ('employee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='authApp.employee')),
            ],
        ),
    ]
