# Generated by Django 3.2.5 on 2022-04-29 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_pointage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_first_name',
            new_name='employee_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_last_name',
            new_name='function',
        ),
        migrations.AlterField(
            model_name='pointage',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.employee'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='entry_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='exit_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authApp.department'),
        ),
    ]
