# Generated by Django 3.2.5 on 2022-04-29 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0006_auto_20220429_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointage',
            name='exit_time',
        ),
        migrations.CreateModel(
            name='Pointage_register',
            fields=[
                ('pointage_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=50)),
                ('entry_time', models.CharField(max_length=50)),
                ('exit_time', models.CharField(max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.employee')),
            ],
        ),
    ]
