# Generated by Django 3.2.5 on 2022-04-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0007_auto_20220429_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='lieu',
            field=models.CharField(default='Ambohijatovo', max_length=30),
        ),
        migrations.AddField(
            model_name='pointage',
            name='lieu',
            field=models.CharField(default='Ambohijatovo', max_length=30),
        ),
        migrations.AddField(
            model_name='pointage_register',
            name='lieu',
            field=models.CharField(default='Ambohijatovo', max_length=30),
        ),
    ]
