# Generated by Django 3.2.5 on 2022-04-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0010_pointage_employee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='numero_matricule',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
