# Generated by Django 3.2.5 on 2022-04-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0011_auto_20220429_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointage',
            old_name='employee',
            new_name='employee_num_matr',
        ),
    ]
