# Generated by Django 3.2.5 on 2022-04-29 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0012_rename_employee_pointage_employee_num_matr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointage',
            name='employee_num_matr',
        ),
        migrations.AddField(
            model_name='pointage',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authApp.employee'),
        ),
    ]
