# Generated by Django 3.2.5 on 2022-04-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0013_auto_20220429_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='employee_dep',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pointage_register',
            name='employee_dep',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pointage_register',
            name='employee_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
