# Generated by Django 3.2.5 on 2022-04-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0014_auto_20220429_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department_name',
            field=models.CharField(default='DSI', max_length=50),
        ),
    ]
