# Generated by Django 3.2.5 on 2022-04-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0015_employee_department_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointage',
            old_name='employee',
            new_name='numero_matricule',
        ),
        migrations.RenameField(
            model_name='pointage_register',
            old_name='employee',
            new_name='numero_matricule',
        ),
    ]
