# Generated by Django 3.2.5 on 2022-05-03 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0016_auto_20220430_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection_register',
            fields=[
                ('employee_name', models.CharField(max_length=50, null=True)),
                ('connection_register_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=50)),
                ('lieu', models.CharField(max_length=30)),
                ('entry_time', models.CharField(max_length=50)),
                ('exit_time', models.CharField(max_length=50)),
                ('numero_matricule', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authApp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Active_connection',
            fields=[
                ('employee_name', models.CharField(max_length=50, null=True)),
                ('active_connection_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=50)),
                ('lieu', models.CharField(max_length=30)),
                ('entry_time', models.CharField(max_length=50)),
                ('numero_matricule', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authApp.employee')),
            ],
        ),
    ]
