# Generated by Django 3.2.5 on 2022-05-04 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0017_active_connection_connection_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_first_name',
            new_name='user_name',
        ),
    ]
