# Generated by Django 3.2.5 on 2022-05-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0018_rename_user_first_name_user_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_last_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
