# Generated by Django 3.2.5 on 2022-05-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0019_auto_20220504_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='numero_matricule',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
