# Generated by Django 3.2.5 on 2022-05-04 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0020_auto_20220504_0842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointage',
            old_name='employee_dep',
            new_name='employee_dep_name',
        ),
    ]
