# Generated by Django 3.2.5 on 2022-05-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0021_rename_employee_dep_pointage_employee_dep_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='employee_dep',
            field=models.IntegerField(default=1),
        ),
    ]
