# Generated by Django 3.2.5 on 2022-05-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0022_pointage_employee_dep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointage',
            name='employee_dep',
            field=models.IntegerField(),
        ),
    ]
