# Generated by Django 3.2.5 on 2022-05-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0023_alter_pointage_employee_dep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointage_register',
            old_name='pointage_id',
            new_name='pointage_register_id',
        ),
        migrations.AddField(
            model_name='pointage_register',
            name='employee_dep_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pointage_register',
            name='employee_dep',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
