# Generated by Django 3.2.5 on 2022-05-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0024_auto_20220504_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointage',
            name='employee_dep',
            field=models.IntegerField(null=True),
        ),
    ]
