# Generated by Django 3.2.5 on 2022-05-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0025_alter_pointage_employee_dep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='employee_dep',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
