# Generated by Django 3.2.5 on 2022-05-09 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0028_auto_20220509_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_connection',
            name='entry_time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='active_connection',
            name='numero_matricule',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='authApp.employee', unique=True),
        ),
    ]
