# Generated by Django 3.2.5 on 2022-05-11 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0029_auto_20220509_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointage',
            name='numero_matricule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authApp.employee'),
        ),
    ]
