# Generated by Django 3.2.5 on 2022-05-16 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0033_alter_active_connection_numero_matricule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
    ]
