# Generated by Django 3.2.5 on 2022-05-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0034_remove_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pointed_at',
            field=models.CharField(default='not pointed', max_length=30),
        ),
    ]
