# Generated by Django 3.2.5 on 2022-05-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0037_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
