# Generated by Django 3.2.5 on 2022-05-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0038_employee_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='isActive',
        ),
    ]
