# Generated by Django 3.2.5 on 2022-05-24 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0040_auto_20220519_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='lieu',
        ),
    ]
