# Generated by Django 3.2.5 on 2022-05-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0042_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='function',
            field=models.CharField(max_length=100),
        ),
    ]
