# Generated by Django 3.2.5 on 2022-05-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0046_alter_employee_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='function',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
