# Generated by Django 3.2.5 on 2022-05-26 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0047_pointage_function'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('stagiaire_id', models.AutoField(primary_key=True, serialize=False)),
                ('stagiaire_name', models.CharField(max_length=100, unique=True)),
                ('department_name', models.CharField(max_length=50)),
                ('descritpion', models.CharField(max_length=200)),
                ('pointed_at', models.CharField(default='not pointed', max_length=30)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
                ('department', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='authApp.department')),
            ],
        ),
    ]
