# Generated by Django 3.2.5 on 2022-05-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0049_stagiaire_duree'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagiaire',
            name='isActif',
            field=models.BooleanField(default=True),
        ),
    ]
