# Generated by Django 3.2.5 on 2022-05-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0050_stagiaire_isactif'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagiaire',
            name='function',
            field=models.CharField(default='stagiaire', max_length=50),
        ),
    ]
