# Generated by Django 3.2.5 on 2022-05-27 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0051_stagiaire_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointage',
            name='numero_matricule',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='authApp.employee'),
        ),
    ]
