# Generated by Django 3.2.5 on 2022-05-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0052_alter_pointage_numero_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='end_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pointage',
            name='start_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
