# Generated by Django 3.2.5 on 2022-05-27 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0054_auto_20220527_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage_register',
            name='function',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pointage_register',
            name='numero_matricule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authApp.employee'),
        ),
    ]
