# Generated by Django 3.2.5 on 2022-05-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0055_auto_20220527_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='duree',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
