# Generated by Django 3.2.5 on 2022-05-27 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0056_alter_stagiaire_duree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagiaire',
            name='department',
        ),
    ]
