# Generated by Django 3.2.5 on 2022-05-27 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0057_remove_stagiaire_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stagiaire',
            old_name='descritpion',
            new_name='description',
        ),
    ]
