# Generated by Django 3.2.5 on 2022-06-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0060_remove_employee_photoname'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photoName',
            field=models.CharField(default='anonymous.png', max_length=30),
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='photoName',
            field=models.CharField(default='anonymous.png', max_length=30),
        ),
    ]
