# Generated by Django 3.2.5 on 2022-06-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0062_auto_20220603_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
