# Generated by Django 3.2.5 on 2022-06-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0064_alter_pointage_numero_matricule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('vehicule_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=50)),
                ('numero_matricule', models.CharField(max_length=20)),
                ('vehicule_name', models.CharField(max_length=100)),
                ('vehicule_marque', models.CharField(max_length=100)),
                ('pointed_at', models.CharField(default='Pas encore actif', max_length=30)),
                ('photoName', models.CharField(default='anonymous.png', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='pointed_at',
            field=models.CharField(default='Pas encore actif', max_length=30),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='pointed_at',
            field=models.CharField(default='Pas encore actif', max_length=30),
        ),
    ]
