# Generated by Django 3.2.5 on 2022-06-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0065_auto_20220609_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointage',
            name='function',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
