# Generated by Django 3.2.5 on 2022-06-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0066_alter_pointage_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointage_register',
            name='numero_matricule',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
