# Generated by Django 3.2.5 on 2022-06-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0067_alter_pointage_register_numero_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointage',
            name='employee_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
