# Generated by Django 3.2.5 on 2022-06-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0068_alter_pointage_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='photoName',
            field=models.CharField(default='anonymous_car.png', max_length=30),
        ),
    ]
