# Generated by Django 4.0.3 on 2022-03-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('visitor_id', models.AutoField(primary_key=True, serialize=False)),
                ('visitor_first_name', models.CharField(max_length=50)),
                ('visitor_last_name', models.CharField(max_length=50)),
                ('motif', models.CharField(max_length=200)),
                ('CIN', models.IntegerField()),
            ],
        ),
    ]
