# Generated by Django 4.0.3 on 2022-03-31 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisitApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('visitor_first_name', models.CharField(max_length=50)),
                ('visitor_last_name', models.CharField(max_length=50)),
                ('motif', models.CharField(max_length=200)),
                ('CIN', models.IntegerField()),
                ('date_of_entry', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('exit_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Visitors',
        ),
    ]
