# Generated by Django 4.0.3 on 2022-04-06 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisitApp', '0002_visits_delete_visitors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visits_register',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('visitor_first_name', models.CharField(max_length=50)),
                ('visitor_last_name', models.CharField(max_length=50)),
                ('motif', models.CharField(max_length=200)),
                ('CIN', models.IntegerField()),
                ('date_of_entry', models.CharField(max_length=50)),
                ('exit_time', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='visits',
            name='date_of_entry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 6, 8, 28, 33, 174745)),
        ),
        migrations.AlterField(
            model_name='visits',
            name='exit_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
