# Generated by Django 4.0.3 on 2022-04-06 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisitApp', '0003_visits_register_alter_visits_date_of_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='date_of_entry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 6, 8, 29, 52, 884219)),
        ),
        migrations.AlterField(
            model_name='visits_register',
            name='date_of_entry',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visits_register',
            name='exit_time',
            field=models.CharField(max_length=100),
        ),
    ]
