# Generated by Django 4.0.3 on 2022-04-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisitApp', '0004_alter_visits_date_of_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='date_of_entry',
            field=models.CharField(max_length=100),
        ),
    ]
