# Generated by Django 3.2.5 on 2022-04-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VisitApp', '0005_alter_visits_date_of_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visits',
            old_name='visitor_first_name',
            new_name='visitor_name',
        ),
        migrations.RenameField(
            model_name='visits_register',
            old_name='visitor_first_name',
            new_name='visitor_name',
        ),
        migrations.RemoveField(
            model_name='visits',
            name='visitor_last_name',
        ),
        migrations.RemoveField(
            model_name='visits_register',
            name='visitor_last_name',
        ),
    ]
