# Generated by Django 3.2.5 on 2022-05-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisitApp', '0008_remove_visits_exit_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visits',
            name='date_of_entry',
        ),
        migrations.RemoveField(
            model_name='visits_register',
            name='date_of_entry',
        ),
        migrations.AddField(
            model_name='visits',
            name='date',
            field=models.CharField(default='01/05/2022', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visits',
            name='entry_time',
            field=models.CharField(default='7h00', max_length=30),
        ),
        migrations.AddField(
            model_name='visits_register',
            name='date',
            field=models.CharField(default='01/05/2022', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visits_register',
            name='entry_time',
            field=models.CharField(default='7h00', max_length=30),
        ),
    ]
