# Generated by Django 3.2.5 on 2022-05-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisitApp', '0010_auto_20220503_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='lieu',
            fields=[
                ('lieu_id', models.AutoField(primary_key=True, serialize=False)),
                ('lieu_name', models.CharField(max_length=50)),
            ],
        ),
    ]
