# Generated by Django 3.2.5 on 2022-05-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisitApp', '0011_lieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='total_employee',
            field=models.IntegerField(default=100),
        ),
    ]
