# Generated by Django 3.2.5 on 2022-05-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisitApp', '0012_lieu_total_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
