# Generated by Django 3.2.5 on 2022-05-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisitApp', '0014_lieu_entry_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visits',
            name='visit_id',
        ),
        migrations.AlterField(
            model_name='visits',
            name='CIN',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
