# Generated by Django 3.2.5 on 2022-05-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisitApp', '0015_auto_20220520_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('visitor_id', models.AutoField(primary_key=True, serialize=False)),
                ('visitor_name', models.CharField(max_length=50)),
                ('CIN', models.IntegerField(null=True)),
                ('comment', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visits_actif',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('visitor_name', models.CharField(max_length=50)),
                ('motif', models.CharField(max_length=300)),
                ('CIN', models.IntegerField(null=True)),
                ('comment', models.CharField(max_length=200, null=True)),
                ('lieu', models.CharField(max_length=30, null=True)),
                ('date', models.CharField(max_length=30)),
                ('entry_time', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Visits',
        ),
    ]
