# Generated by Django 3.2.5 on 2022-05-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisitApp', '0017_alter_visitors_cin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits_actif',
            name='CIN',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='visits_register',
            name='CIN',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
