# Generated by Django 3.2.5 on 2022-05-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisitApp', '0019_visitors_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='visitor_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
