# Generated by Django 3.2.5 on 2022-06-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisitApp', '0020_alter_visitors_visitor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits_actif',
            name='visitor_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
