# Generated by Django 3.2.5 on 2022-06-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisitApp', '0021_alter_visits_actif_visitor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='description',
            field=models.CharField(default='pas de description', max_length=200),
        ),
    ]
