# Generated by Django 3.2.5 on 2022-06-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisitApp', '0022_alter_visitors_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='visits_register',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
